# Generated by Django 3.2 on 2021-04-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_competence', models.CharField(max_length=50, verbose_name='CompetenceTitle')),
                ('level_of_competence', models.CharField(choices=[('1', 'begginer'), ('2', 'low'), ('3', 'middle'), ('4', 'upper'), ('5', 'pro')], default='1', max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.user')),
            ],
        ),
    ]
