# Generated by Django 3.2 on 2021-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210423_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_vacancy', models.CharField(max_length=50, verbose_name='VacancyTitle')),
                ('description', models.TextField(max_length=400, verbose_name='Description')),
                ('city_of_vacancy', models.CharField(max_length=25, verbose_name='City')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('web_site', models.CharField(max_length=20, verbose_name='WebSite')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
    ]
