# Generated by Django 3.2 on 2021-05-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vacancy_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='percent',
        ),
    ]
