# Generated by Django 3.2 on 2021-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vacancy_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Percentage'),
        ),
    ]
