# Generated by Django 3.2 on 2021-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vacancy_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='level_of_competence',
            field=models.CharField(choices=[(1, 'begginer'), (2, 'low'), (3, 'middle'), (4, 'upper'), (5, 'pro')], default=1, max_length=2),
        ),
    ]
