# Generated by Django 3.2 on 2021-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_competence_level_of_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='num_of_stars',
            field=models.IntegerField(default=1),
        ),
    ]
