# Generated by Django 3.2 on 2021-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_competence_num_of_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='percent',
            field=models.IntegerField(null=True, verbose_name='Percentage'),
        ),
    ]
