# Generated by Django 3.2 on 2021-06-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vacancy_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='level_of_competence',
            field=models.IntegerField(choices=[(1, 'begginer'), (2, 'low'), (3, 'middle'), (4, 'upper'), (5, 'pro')], default=1),
        ),
    ]
